### PR TITLE
Just a heads up

### PR DESCRIPTION
**Pull request by jimmykane**
Hey, 

Nice changed in the repo. 

I had also progressed the module and I am sending you this PR just in case you would like to rebase your changed on top of my fork which is also a new module (new name). 

In this case we would both benefit and keep the FIT file parsing alive. 

We are also working with the original creator to convert this to typescript.

What do you think? 

I can also try to pull your changes, but I would be more prone to errors.

### CODE REVIEW

**Comment by babgvant** [comment]
Thanks! This is great. I'll have a look and get it merged as soon as I get some time.

**Comment by jimmykane** [comment]
Perhaps the best is to not merge here (also possible) but try to merge on
the PR branch.

Perhaps its better because for example I had solved the L/R balance ,
percentages etc there.

If you are having trouble I can help.

And don't worry no time pressure or anything. I just wanted to share
nothing more :-)

**Comment by jimmykane** [comment]
Hi @babgvant I went on and cherry picked all the code changes you did and merged them back with references to your commits.  

The conflicts this merge to you reports is basically the rename of the repo etc. Nothing more. 

Feel free to test or just for ahead and use https://github.com/jimmykane/fit-parser `npm install fit-file-parser` that should contain your changes.

**Comment by babgvant** [comment]
Thanks. Will have a look as soon as I can.

Cheers

**Comment by jimmykane** [comment]
The thing I could not test is a file with monitoring info and file_ids , don't have such a fit file. 

and hey ! Thanks for the compressed fields!

**Comment by babgvant** [comment]
hopefully i didn't break anything there :)

**Pull request merged**
